import type { Metadata } from "next";
import Link from "next/link";
import { CalculatorCard } from "@/components/calculator-card";
import { calculatorDefinitions, calculatorsBySlug, categories } from "@/lib/calculator-definitions";
import { getSession, signInUrl } from "@/lib/session";

export const metadata: Metadata = { title: "CalcForged — Practical calculators. Straight answers.", description: "Fast, free calculators for food planning, home improvement, construction, events, and business decisions." };

export default async function Home() {
  const total = calculatorDefinitions.length;
  const FEATURED_SLUGS = ["recipe-scaling", "paint", "mortgage", "wedding-food", "bbq-meat", "tip"];
  const featured = FEATURED_SLUGS.map((slug) => calculatorsBySlug[slug]).filter(Boolean);
  const isSignedIn = Boolean(await getSession());
  const signIn = await signInUrl("/dashboard/toolkit");
  return <>
    <section className="cf-hero"><div className="cf-shell cf-hero-grid"><div><p className="cf-eyebrow"><span className="cf-eyebrow-line" /> Tools for real-world decisions</p><h1>Practical calculators.<br /><em>Straight answers.</em></h1><p className="cf-hero-copy">Useful, transparent calculators for the moments when you need a number you can trust—without signing up, sorting through fluff, or doing the math twice.</p><div className="cf-hero-actions"><Link href="/calculators" className="cf-button cf-button-dark">Browse all calculators <span>↗</span></Link><a href="#tools" className="cf-text-link">Jump to the essentials <span>↓</span></a></div></div><div className="cf-hero-note"><div className="cf-note-rule" /><p>Built for the question behind the question.</p><span>01 — Measure</span><span>02 — Understand</span><span>03 — Act</span></div></div></section>
    <section className="cf-trust"><div className="cf-shell cf-trust-grid"><div><strong>{total}</strong><span>specialized tools</span></div><div><strong>0</strong><span>sign-ups required</span></div><div><strong>∞</strong><span>ways to use the answer</span></div><p>Every formula is shown.<br />Every result is yours.</p></div></section>
    <section className="cf-section" id="tools"><div className="cf-shell"><div className="cf-section-heading"><div><p className="cf-kicker">Start here</p><h2>The six you’ll reach<br /><em>for first.</em></h2></div><Link href="/calculators" className="cf-text-link">View all {total} calculators <span>↗</span></Link></div><div className="cf-tools-grid cf-featured-grid">{featured.map((definition) => <CalculatorCard key={definition.slug} definition={definition} />)}</div><div className="cf-featured-footer"><p>Everything else lives in the library below — all {total} tools, free, no sign-up.</p><Link href="/calculators" className="cf-text-link">All calculators <span>↗</span></Link></div></div></section>
    <section className="cf-leadmagnet cf-account-band"><div className="cf-leadmagnet-card"><div className="cf-leadmagnet-pitch"><p className="cf-kicker">Free account</p><h2>Your toolkit, one click from <em>home.</em></h2><p>Star the calculators you actually use and they wait for you here — and your last 20 calculations stay saved, ready to reopen with the numbers you used. Free, no card, no spam, nothing to cancel.</p></div><div className="cf-account-band-actions">{isSignedIn ? <Link href="/dashboard/toolkit" className="cf-button cf-button-dark">Open my toolkit <span aria-hidden="true">↗</span></Link> : <><Link href={signIn} className="cf-button cf-button-dark">Create your free account <span aria-hidden="true">↗</span></Link><Link href={signIn} className="cf-text-link">Already with us? Log in <span aria-hidden="true">↗</span></Link></>}</div></div></section>
    <section className="cf-section cf-category-section"><div className="cf-shell"><div className="cf-section-heading"><div><p className="cf-kicker">The library</p><h2>Find your<br /><em>category.</em></h2></div><p className="cf-heading-aside">A growing reference shelf for food, home, business, and everyday planning.</p></div><div className="cf-category-grid">{categories.map((category, index) => { const count = calculatorDefinitions.filter((item) => item.categorySlug === category.slug).length; return <Link href={`/calculators/${category.slug}`} key={category.slug} className="cf-category-row"><span className="cf-category-index">{String(index + 1).padStart(2, "0")}</span><span><strong>{category.name}</strong><small>{count ? `${count} calculator${count > 1 ? "s" : ""}` : "Coming soon"}</small></span><span className="cf-category-arrow">→</span></Link> })}</div></div></section>
    <section className="cf-why" id="why"><div className="cf-shell cf-why-grid"><div><p className="cf-kicker">No nonsense by design</p><h2>Tools should get out of the way.</h2></div><div className="cf-why-points"><p><strong>Clear inputs.</strong> No jargon, no account walls, no mystery fields.</p><p><strong>Visible math.</strong> See the formula and the assumptions behind every estimate.</p><p><strong>Useful output.</strong> Copy it, print it, or share the exact result with someone else.</p></div></div></section>
  </>;
}
