import type { Metadata } from "next";
import Link from "next/link";
import { CalculatorCard } from "@/components/calculator-card";
import { calculatorDefinitions, categories } from "@/lib/calculator-definitions";

export const metadata: Metadata = { title: "CalcForge — Practical calculators. Straight answers.", description: "Fast, free calculators for food planning, home improvement, construction, events, and business decisions." };

export default function Home() {
  return <>
    <section className="cf-hero"><div className="cf-shell cf-hero-grid"><div><p className="cf-eyebrow"><span className="cf-eyebrow-line" /> Tools for real-world decisions</p><h1>Practical calculators.<br /><em>Straight answers.</em></h1><p className="cf-hero-copy">Useful, transparent calculators for the moments when you need a number you can trust—without signing up, sorting through fluff, or doing the math twice.</p><div className="cf-hero-actions"><Link href="/calculators" className="cf-button cf-button-dark">Browse all calculators <span>↗</span></Link><a href="#tools" className="cf-text-link">See the 10 MVP tools <span>↓</span></a></div></div><div className="cf-hero-note"><div className="cf-note-rule" /><p>Built for the question behind the question.</p><span>01 — Measure</span><span>02 — Understand</span><span>03 — Act</span></div></div></section>
    <section className="cf-trust"><div className="cf-shell cf-trust-grid"><div><strong>10</strong><span>specialized tools</span></div><div><strong>0</strong><span>sign-ups required</span></div><div><strong>∞</strong><span>ways to use the answer</span></div><p>Every formula is shown.<br />Every result is yours.</p></div></section>
    <section className="cf-section" id="tools"><div className="cf-shell"><div className="cf-section-heading"><div><p className="cf-kicker">The starting set</p><h2>Numbers for the work<br /><em>you’re already doing.</em></h2></div><Link href="/calculators" className="cf-text-link">View all tools <span>↗</span></Link></div><div className="cf-tools-grid">{calculatorDefinitions.map((definition) => <CalculatorCard key={definition.slug} definition={definition} />)}</div></div></section>
    <section className="cf-section cf-category-section"><div className="cf-shell"><div className="cf-section-heading"><div><p className="cf-kicker">The library</p><h2>Find your<br /><em>category.</em></h2></div><p className="cf-heading-aside">A growing reference shelf for food, home, business, and everyday planning.</p></div><div className="cf-category-grid">{categories.map((category, index) => { const count = calculatorDefinitions.filter((item) => item.categorySlug === category.slug).length; return <Link href={`/calculators/${category.slug}`} key={category.slug} className="cf-category-row"><span className="cf-category-index">{String(index + 1).padStart(2, "0")}</span><span><strong>{category.name}</strong><small>{count ? `${count} calculator${count > 1 ? "s" : ""}` : "Coming soon"}</small></span><span className="cf-category-arrow">→</span></Link> })}</div></div></section>
    <section className="cf-why" id="why"><div className="cf-shell cf-why-grid"><div><p className="cf-kicker">No nonsense by design</p><h2>Tools should get out of the way.</h2></div><div className="cf-why-points"><p><strong>Clear inputs.</strong> No jargon, no account walls, no mystery fields.</p><p><strong>Visible math.</strong> See the formula and the assumptions behind every estimate.</p><p><strong>Useful output.</strong> Copy it, print it, or share the exact result with someone else.</p></div></div></section>
  </>;
}
