"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { calculatorDefinitions, categories } from "@/lib/calculator-definitions";

export default function AdminPage() {
  const [query, setQuery] = useState("");
  const [disabled, setDisabled] = useState<string[]>([]);
  const visible = useMemo(() => calculatorDefinitions.filter((item) => `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <section className="cf-page cf-admin"><div className="cf-shell"><div className="cf-admin-top"><div><p className="cf-kicker">CalcForged operations</p><h1>Calculator dashboard</h1><p>Manage the live calculator registry and review the structure of the library.</p></div><span className="cf-admin-badge">MVP admin</span></div><div className="cf-admin-stats"><div><strong>{calculatorDefinitions.length}</strong><span>registered tools</span></div><div><strong>{categories.length}</strong><span>categories</span></div><div><strong>0</strong><span>tracked sessions</span></div><div><strong>∞</strong><span>room to expand</span></div></div><div className="cf-admin-toolbar"><input placeholder="Search calculators" value={query} onChange={(event) => setQuery(event.target.value)} /><span>Config registry · JSON-ready architecture</span></div><div className="cf-admin-table"><div className="cf-admin-table-head"><span>Calculator</span><span>Category</span><span>Status</span><span>Usage</span><span>Action</span></div>{visible.map((item) => { const isDisabled = disabled.includes(item.slug); return <div className="cf-admin-row" key={item.slug}><div><span className="cf-tool-icon cf-tool-icon-small">{item.icon}</span><div><strong>{item.name}</strong><small>/{item.categorySlug}/{item.slug}</small></div></div><span>{item.category}</span><span className={isDisabled ? "cf-status cf-status-off" : "cf-status"}>{isDisabled ? "Disabled" : "Enabled"}</span><span className="cf-muted">No events yet</span><button type="button" onClick={() => setDisabled((current) => isDisabled ? current.filter((slug) => slug !== item.slug) : [...current, item.slug])}>{isDisabled ? "Enable" : "Disable"}</button></div> })}</div><div className="cf-admin-note"><div><p className="cf-kicker">How to add calculator #11</p><h2>One config. One registry line.</h2></div><p>Each calculator is a typed definition with fields, formulas, result labels, SEO copy, FAQs, and related links. To add the next tool, create a definition in <code>lib/calculator-definitions.ts</code> and register it in the shared list. The routes, index, metadata, and calculator UI follow automatically.</p></div><Link href="/calculators" className="cf-back-link">← Back to calculator library</Link></div></section>;
}
