import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { CalculatorCard } from "@/components/calculator-card";
import { CalculatorClient } from "@/components/calculator-client";
import { calculatorDefinitions, calculatorsBySlug } from "@/lib/calculator-definitions";

export function generateStaticParams() { return calculatorDefinitions.map((definition) => ({ category: definition.categorySlug, slug: definition.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const definition = calculatorsBySlug[slug]; return definition ? { title: definition.seo.title, description: definition.seo.description } : {}; }

export default async function CalculatorPage({ params }: { params: Promise<{ category: string; slug: string }> }) {
  const { category, slug } = await params; const definition = calculatorsBySlug[slug]; if (!definition || definition.categorySlug !== category) notFound();
  const related = definition.related.map((item) => calculatorsBySlug[item]).filter(Boolean);
  const faqJsonLd = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: definition.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) };
  const appJsonLd = { "@context": "https://schema.org", "@type": "WebApplication", name: definition.name, applicationCategory: "UtilitiesApplication", operatingSystem: "Any", description: definition.seo.description, offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } };
  const breadcrumbJsonLd = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "/" }, { "@type": "ListItem", position: 2, name: definition.category, item: `/calculators/${definition.categorySlug}` }, { "@type": "ListItem", position: 3, name: definition.name }] };
  return <article className="cf-calculator-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(appJsonLd) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} /><div className="cf-shell"><div className="cf-breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href={`/calculators/${definition.categorySlug}`}>{definition.category}</Link><span>/</span><span>{definition.name}</span></div><div className="cf-calculator-intro"><p className="cf-kicker">{definition.category}</p><h1>{definition.seo.h1}</h1><p>{definition.seo.intro}</p></div><CalculatorClient slug={definition.slug} /><div className="cf-content-grid"><div><section className="cf-copy-section"><p className="cf-kicker">The math, plainly</p><h2>How it works</h2><ol>{definition.howItWorks.map((line, index) => <li key={line}><span>{String(index + 1).padStart(2, "0")}</span><p>{line}</p></li>)}</ol></section><section className="cf-copy-section cf-example"><p className="cf-kicker">Try a real scenario</p><h2>{definition.example.title}</h2><div className="cf-example-box"><p><strong>Inputs</strong>{definition.example.inputs}</p><p><strong>Result</strong>{definition.example.result}</p></div></section></div><aside className="cf-faq"><p className="cf-kicker">Questions, answered</p><h2>FAQ</h2>{definition.faqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</aside></div><section className="cf-related"><div className="cf-section-heading"><div><p className="cf-kicker">Keep going</p><h2>Related calculators</h2></div></div><div className="cf-tools-grid">{related.map((item) => <CalculatorCard key={item.slug} definition={item} />)}</div></section></div></article>;
}
